### ISSUE TITLE
Why does `archives_create_days` care when a file was created?

### ISSUE THREAD

**Issue by 501st-alpha1** [Kraymer/cronicle#8]
I was trying to see if I could get this to work with some hourly backups that I have.  (The TL;DR is: yes, `hourly|0: 5` works and gives me 5 hourly backups, aside from the issue in this question.)

Where it breaks is in `rotate`, because `archives_create_days` returns a Dict split by day, so it only considers one file from any given day.

Is there a reason it needs to work this way?  When it's used here:

https://github.com/Kraymer/cronicle/blob/060cb5859c292c6508160b2b7eda3406507f415a/cronicle/__init__.py#L117

it's just to skip the n most recent, so if there isn't more than one file per day, it acts the same as a plain directory listing.  When it's used here:

https://github.com/Kraymer/cronicle/blob/060cb5859c292c6508160b2b7eda3406507f415a/cronicle/__init__.py#L83

it's just to get the last date a file was created, which could be done by calling `file_create_day` on the last filename.

Did I miss something else?  Would you be open to a PR that changes this?  I don't really mind if there's no built-in support for hourly rotations, as long as I can make the custom periodicity work.

---

Also, this is a cool project, thanks for building this!  It's much nicer than the Bash script I was considering writing myself, haha.

**Comment by Kraymer** [comment]
Hi @501st-alpha1 , glad you like this project !
Always motivating to see someone using your product :) 
You raised good points. I would be interested to go back on working on `cronicle` but the first thing would be to have proper unit tests to easily show off which use cases fail.
So the first step imo, would be to have a failing unit test related to your hourly setup.

**Comment by Kraymer** [comment]
I think it's good now.
Feel free to reopen if it's not the case.
